Add quick start example
vechain/x-app-template pull request #25
Opened 2024-09-10 10:20 UTC by ifavo

This PR aims to simplify the start for impatient developers on the app template:

- Adds a `QuickStart.md` with reduced information and a single snippet to get started
- Documents the links that will be available
- Defaults the log dir, to use less config variables

2024-09-10 16:37 UTC, Agilulfo1820 approved these changes

2024-09-12 14:39 UTC, pierobassa commented on QuickStart.md
> + yarn dev
Like the idea of the quickstart! But 

`OPENAI_API_KEY="sk-proj-.."` would configure the backend with a wrong API key

Users might mistake the steps as a copy and paste and everything will work.

Possible solution could be adding the "Result" section of the Quickstart below the Readme here:
![image](https://github.com/user-attachments/assets/7a5d4021-51cb-4fc8-bde6-9e4170075653)

2024-09-12 14:40 UTC, pierobassa requested changes
Adding Request Change

2024-09-13 11:43 UTC, pierobassa commented
> > Possible solution could be adding the "Result" section of the Quickstart below the Readme here:
> 
> 👋 not sure what you mean by that. Would this be adding the link table to the first section?
> 
> I agree with the potential copy & paste misunderstanding. It is stated at the top as required variable.
> 
> I went back with my original frustration about the required amount of ENV and found that `envalid` is used to verify `PORT` and `NODE_ENV` only. I've modified it slightly to verify all the ENV and also use the verified ENV. In the process adjusted, it now also sets some default values **and** has an OpenAPI-Key verifier, that informs the user where to obtain one.
> 
> What do you think about the change?

Nice catch! Could you have a reference to the `Quickstart.md `in the `Readme.md` too?

2024-09-13 12:01 UTC, ifavo commented
I did add a link to the README, hope its what you expect. Feel free to adjust the way you like to see it!

2024-09-13 18:10 UTC, pierobassa approved these changes

2024-09-13 18:12 UTC, merged